import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  // ── Global ignores ────────────────────────────────────────────────────────────
  {
    ignores: [
      '**/dist/**',
      '**/bundle/**',
      '**/node_modules/**',
      'prisma/migrations/**',
      '**/.next/**',
      'apps/web/next-env.d.ts', // Auto-generated by Next.js
      'apps/tutor/**', // Python AI tutor service
    ],
  },

  // ── Base JS + TS rules for all workspaces ─────────────────────────────────────
  eslint.configs.recommended,
  ...tseslint.configs.recommended,

  // ── Prettier: disable conflicting rules + run Prettier as a lint rule ─────────
  prettierConfig,
  {
    plugins: { prettier: prettierPlugin },
    rules: { 'prettier/prettier': 'error' },
  },

  // ── Relax some strict TS rules that fire too often in a mixed JS/TS monorepo ──
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-require-imports': 'warn',
    },
  },

  // ── React + hooks rules scoped to apps/web ────────────────────────────────────
  {
    files: ['apps/web/**/*.{ts,tsx,js,jsx,mjs}'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      ...reactHooksPlugin.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off', // Not needed in Next.js / React 17+
      'react/prop-types': 'off', // TypeScript covers this
    },
  },

  // ── Legacy CommonJS src/, bin/, scripts/, test/ — Node.js globals ─────────────
  {
    files: [
      'src/**/*.js',
      'bin/**/*.js',
      'scripts/**/*.js',
      'scripts/**/*.mjs',
      'test/**/*.js',
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-var-requires': 'off',
    },
  },
);
