import type { BadgeCategory, BadgeRarity } from '@prisma/client';
import {
  REPUTATION_LEVEL_NAMES,
  REPUTATION_LEVEL_THRESHOLDS,
  computeReputationLevel,
  getReputationLevelName,
  getReputationLevelProgress,
} from '@nibras/contracts';
import { assembleBadgeCatalog } from './badge-catalog-builder';

export type BadgeMetric =
  | 'githubLinked'
  | 'githubAppInstalled'
  | 'courseEnrollments'
  | 'passedSubmissions'
  | 'totalSubmissions'
  | 'failedSubmissions'
  | 'teamMemberships'
  | 'questions'
  | 'answers'
  | 'acceptedAnswers'
  | 'questionUpvotesReceived'
  | 'communityVotes'
  | 'threads'
  | 'threadPosts'
  | 'solvedProblems'
  | 'problemBookmarks'
  | 'contestParticipations'
  | 'contestBookmarks'
  | 'assignmentSubmissions'
  | 'videosWatched'
  | 'earnedBadges'
  | 'dailyStreakCurrent'
  | 'dailyStreakLongest'
  | 'dailyProblemsCompleted'
  | 'codeforcesMaxRating'
  | 'leetcodeMaxRating'
  | 'plansSubmittedForAdvisor'
  | 'programSheetsGenerated'
  | 'cpRoadmapSolvedCount'
  | 'cpRoadmapTopicsComplete'
  | 'cpRoadmapPercent'
  | 'cpRoadmapCategoriesComplete';

export type BadgeSeed = {
  code: string;
  name: string;
  description: string;
  rarity: BadgeRarity;
  category: BadgeCategory;
  metric: BadgeMetric;
  threshold: number;
  points: number;
  sortOrder: number;
};

/** Original hand-authored catalog (includes legacy meta badges; replaced on assemble). */
export const LEGACY_BADGES: BadgeSeed[] = [
  // ── Onboarding ──────────────────────────────────────────────────────────────
  {
    code: 'github-connected',
    name: 'GitHub Connected',
    description: 'Link your GitHub account to Nibras.',
    rarity: 'common',
    category: 'onboarding',
    metric: 'githubLinked',
    threshold: 1,
    points: 25,
    sortOrder: 1,
  },
  {
    code: 'github-app-ready',
    name: 'GitHub App Ready',
    description: 'Install the Nibras GitHub app on your account.',
    rarity: 'common',
    category: 'onboarding',
    metric: 'githubAppInstalled',
    threshold: 1,
    points: 35,
    sortOrder: 2,
  },
  {
    code: 'first-enrollment',
    name: 'First Enrollment',
    description: 'Join your first course on Nibras.',
    rarity: 'common',
    category: 'onboarding',
    metric: 'courseEnrollments',
    threshold: 1,
    points: 30,
    sortOrder: 3,
  },
  {
    code: 'plan-submitted',
    name: 'Plan Submitted',
    description: 'Submit your degree plan for advisor review.',
    rarity: 'common',
    category: 'onboarding',
    metric: 'plansSubmittedForAdvisor',
    threshold: 1,
    points: 40,
    sortOrder: 7,
  },
  {
    code: 'sheet-generated',
    name: 'Program Sheet',
    description: 'Generate your printable program sheet.',
    rarity: 'common',
    category: 'onboarding',
    metric: 'programSheetsGenerated',
    threshold: 1,
    points: 35,
    sortOrder: 8,
  },
  {
    code: 'course-explorer',
    name: 'Course Explorer',
    description: 'Enroll in three different courses.',
    rarity: 'rare',
    category: 'onboarding',
    metric: 'courseEnrollments',
    threshold: 3,
    points: 75,
    sortOrder: 4,
  },
  {
    code: 'first-lesson',
    name: 'First Lesson',
    description: 'Mark your first course video as watched.',
    rarity: 'common',
    category: 'onboarding',
    metric: 'videosWatched',
    threshold: 1,
    points: 25,
    sortOrder: 5,
  },
  {
    code: 'binge-learner',
    name: 'Binge Learner',
    description: 'Watch ten course videos.',
    rarity: 'rare',
    category: 'onboarding',
    metric: 'videosWatched',
    threshold: 10,
    points: 100,
    sortOrder: 6,
  },

  // ── Projects ────────────────────────────────────────────────────────────────
  {
    code: 'first-steps',
    name: 'First Steps',
    description: 'Pass your first project submission.',
    rarity: 'common',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 1,
    points: 50,
    sortOrder: 10,
  },
  {
    code: 'first-attempt',
    name: 'First Attempt',
    description: 'Submit a project for grading.',
    rarity: 'common',
    category: 'projects',
    metric: 'totalSubmissions',
    threshold: 1,
    points: 25,
    sortOrder: 11,
  },
  {
    code: 'momentum',
    name: 'Building Momentum',
    description: 'Pass three project submissions.',
    rarity: 'common',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 3,
    points: 75,
    sortOrder: 12,
  },
  {
    code: 'ship-it',
    name: 'Ship It',
    description: 'Pass five project submissions.',
    rarity: 'rare',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 5,
    points: 100,
    sortOrder: 13,
  },
  {
    code: 'keep-pushing',
    name: 'Keep Pushing',
    description: 'Submit twenty project attempts.',
    rarity: 'rare',
    category: 'projects',
    metric: 'totalSubmissions',
    threshold: 20,
    points: 125,
    sortOrder: 14,
  },
  {
    code: 'project-veteran',
    name: 'Project Veteran',
    description: 'Pass ten project submissions.',
    rarity: 'epic',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 10,
    points: 200,
    sortOrder: 15,
  },
  {
    code: 'steady-shipper',
    name: 'Steady Shipper',
    description: 'Pass fifteen project submissions.',
    rarity: 'epic',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 15,
    points: 250,
    sortOrder: 16,
  },
  {
    code: 'code-architect',
    name: 'Code Architect',
    description: 'Pass twenty-five project submissions.',
    rarity: 'legendary',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 25,
    points: 400,
    sortOrder: 17,
  },
  {
    code: 'half-century',
    name: 'Half Century',
    description: 'Pass fifty project submissions.',
    rarity: 'legendary',
    category: 'projects',
    metric: 'passedSubmissions',
    threshold: 50,
    points: 600,
    sortOrder: 18,
  },
  {
    code: 'resilient-coder',
    name: 'Resilient Coder',
    description: 'Learn from five failed submission attempts.',
    rarity: 'rare',
    category: 'projects',
    metric: 'failedSubmissions',
    threshold: 5,
    points: 75,
    sortOrder: 19,
  },
  {
    code: 'team-roster',
    name: 'Team Roster',
    description: 'Join a project team.',
    rarity: 'common',
    category: 'projects',
    metric: 'teamMemberships',
    threshold: 1,
    points: 40,
    sortOrder: 20,
  },
  {
    code: 'squad-member',
    name: 'Squad Member',
    description: 'Be a member of three different project teams.',
    rarity: 'rare',
    category: 'projects',
    metric: 'teamMemberships',
    threshold: 3,
    points: 100,
    sortOrder: 21,
  },
  {
    code: 'assignment-submitted',
    name: 'Homework Hand-In',
    description: 'Submit your first course assignment.',
    rarity: 'common',
    category: 'projects',
    metric: 'assignmentSubmissions',
    threshold: 1,
    points: 35,
    sortOrder: 22,
  },
  {
    code: 'assignment-regular',
    name: 'Assignment Regular',
    description: 'Submit five course assignments.',
    rarity: 'rare',
    category: 'projects',
    metric: 'assignmentSubmissions',
    threshold: 5,
    points: 90,
    sortOrder: 23,
  },

  // ── Community ───────────────────────────────────────────────────────────────
  {
    code: 'curious-mind',
    name: 'Curious Mind',
    description: 'Ask your first community question.',
    rarity: 'common',
    category: 'community',
    metric: 'questions',
    threshold: 1,
    points: 25,
    sortOrder: 30,
  },
  {
    code: 'active-asker',
    name: 'Active Asker',
    description: 'Ask five community questions.',
    rarity: 'common',
    category: 'community',
    metric: 'questions',
    threshold: 5,
    points: 50,
    sortOrder: 31,
  },
  {
    code: 'discussion-leader',
    name: 'Discussion Leader',
    description: 'Ask ten community questions.',
    rarity: 'rare',
    category: 'community',
    metric: 'questions',
    threshold: 10,
    points: 100,
    sortOrder: 32,
  },
  {
    code: 'helpful-peer',
    name: 'Helpful Peer',
    description: 'Post your first community answer.',
    rarity: 'common',
    category: 'community',
    metric: 'answers',
    threshold: 1,
    points: 25,
    sortOrder: 33,
  },
  {
    code: 'mentor-spirit',
    name: 'Mentor Spirit',
    description: 'Post five community answers.',
    rarity: 'common',
    category: 'community',
    metric: 'answers',
    threshold: 5,
    points: 50,
    sortOrder: 34,
  },
  {
    code: 'community-pillar',
    name: 'Community Pillar',
    description: 'Post fifteen community answers.',
    rarity: 'epic',
    category: 'community',
    metric: 'answers',
    threshold: 15,
    points: 175,
    sortOrder: 35,
  },
  {
    code: 'prolific-helper',
    name: 'Prolific Helper',
    description: 'Post twenty-five community answers.',
    rarity: 'epic',
    category: 'community',
    metric: 'answers',
    threshold: 25,
    points: 225,
    sortOrder: 36,
  },
  {
    code: 'accepted-answer',
    name: 'Accepted Answer',
    description: 'Have an answer accepted by the question author.',
    rarity: 'rare',
    category: 'community',
    metric: 'acceptedAnswers',
    threshold: 1,
    points: 75,
    sortOrder: 37,
  },
  {
    code: 'trusted-mentor',
    name: 'Trusted Mentor',
    description: 'Have five answers accepted by question authors.',
    rarity: 'legendary',
    category: 'community',
    metric: 'acceptedAnswers',
    threshold: 5,
    points: 250,
    sortOrder: 38,
  },
  {
    code: 'expert-mentor',
    name: 'Expert Mentor',
    description: 'Have ten answers accepted by question authors.',
    rarity: 'legendary',
    category: 'community',
    metric: 'acceptedAnswers',
    threshold: 10,
    points: 350,
    sortOrder: 39,
  },
  {
    code: 'upvoted-question',
    name: 'Upvoted Question',
    description: 'Receive five upvotes on your questions.',
    rarity: 'common',
    category: 'community',
    metric: 'questionUpvotesReceived',
    threshold: 5,
    points: 40,
    sortOrder: 40,
  },
  {
    code: 'crowd-favorite',
    name: 'Crowd Favorite',
    description: 'Receive twenty-five upvotes on your questions.',
    rarity: 'epic',
    category: 'community',
    metric: 'questionUpvotesReceived',
    threshold: 25,
    points: 200,
    sortOrder: 41,
  },
  {
    code: 'community-voter',
    name: 'Community Voter',
    description: 'Cast ten votes on community posts.',
    rarity: 'common',
    category: 'community',
    metric: 'communityVotes',
    threshold: 10,
    points: 40,
    sortOrder: 42,
  },
  {
    code: 'super-voter',
    name: 'Super Voter',
    description: 'Cast fifty votes on community posts.',
    rarity: 'rare',
    category: 'community',
    metric: 'communityVotes',
    threshold: 50,
    points: 100,
    sortOrder: 43,
  },
  {
    code: 'thread-opener',
    name: 'Thread Opener',
    description: 'Start your first course discussion thread.',
    rarity: 'common',
    category: 'community',
    metric: 'threads',
    threshold: 1,
    points: 30,
    sortOrder: 44,
  },
  {
    code: 'discussion-host',
    name: 'Discussion Host',
    description: 'Start five course discussion threads.',
    rarity: 'rare',
    category: 'community',
    metric: 'threads',
    threshold: 5,
    points: 90,
    sortOrder: 45,
  },
  {
    code: 'active-discussant',
    name: 'Active Discussant',
    description: 'Post ten replies in course discussions.',
    rarity: 'rare',
    category: 'community',
    metric: 'threadPosts',
    threshold: 10,
    points: 90,
    sortOrder: 46,
  },

  // ── Practice ────────────────────────────────────────────────────────────────
  {
    code: 'problem-solver-1',
    name: 'Problem Solver',
    description: 'Solve your first practice problem.',
    rarity: 'common',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 1,
    points: 25,
    sortOrder: 50,
  },
  {
    code: 'warmup-five',
    name: 'Warm-Up Five',
    description: 'Solve five practice problems.',
    rarity: 'common',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 5,
    points: 50,
    sortOrder: 51,
  },
  {
    code: 'problem-solver-10',
    name: 'Practice Pro',
    description: 'Solve ten practice problems.',
    rarity: 'rare',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 10,
    points: 100,
    sortOrder: 52,
  },
  {
    code: 'daily-grinder',
    name: 'Daily Grinder',
    description: 'Solve twenty-five practice problems.',
    rarity: 'rare',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 25,
    points: 150,
    sortOrder: 53,
  },
  {
    code: 'problem-solver-50',
    name: 'Algorithm Ace',
    description: 'Solve fifty practice problems.',
    rarity: 'legendary',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 50,
    points: 300,
    sortOrder: 54,
  },
  {
    code: 'practice-marathon',
    name: 'Practice Marathon',
    description: 'Solve seventy-five practice problems.',
    rarity: 'epic',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 75,
    points: 350,
    sortOrder: 55,
  },
  {
    code: 'grind-master',
    name: 'Grind Master',
    description: 'Solve one hundred practice problems.',
    rarity: 'legendary',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 100,
    points: 500,
    sortOrder: 56,
  },
  {
    code: 'century-solver',
    name: 'Century Solver',
    description: 'Solve two hundred practice problems.',
    rarity: 'legendary',
    category: 'practice',
    metric: 'solvedProblems',
    threshold: 200,
    points: 750,
    sortOrder: 57,
  },
  {
    code: 'problem-curator',
    name: 'Problem Curator',
    description: 'Bookmark five practice problems.',
    rarity: 'common',
    category: 'practice',
    metric: 'problemBookmarks',
    threshold: 5,
    points: 30,
    sortOrder: 58,
  },
  {
    code: 'saved-collection',
    name: 'Saved Collection',
    description: 'Bookmark twenty practice problems.',
    rarity: 'rare',
    category: 'practice',
    metric: 'problemBookmarks',
    threshold: 20,
    points: 75,
    sortOrder: 59,
  },
  {
    code: 'cp-roadmap-first-topic',
    name: 'Roadmap Starter',
    description: 'Complete your first CP Roadmap topic.',
    rarity: 'common',
    category: 'practice',
    metric: 'cpRoadmapTopicsComplete',
    threshold: 1,
    points: 40,
    sortOrder: 60,
  },
  {
    code: 'cp-roadmap-25-percent',
    name: 'Roadmap Quarter',
    description: 'Reach 25% progress on the CP Roadmap.',
    rarity: 'rare',
    category: 'practice',
    metric: 'cpRoadmapPercent',
    threshold: 25,
    points: 100,
    sortOrder: 61,
  },
  {
    code: 'cp-roadmap-complete-category',
    name: 'Category Conqueror',
    description: 'Complete every topic in a CP Roadmap category.',
    rarity: 'epic',
    category: 'practice',
    metric: 'cpRoadmapCategoriesComplete',
    threshold: 1,
    points: 200,
    sortOrder: 62,
  },

  // ── Daily ───────────────────────────────────────────────────────────────────
  {
    code: 'daily-starter',
    name: 'Daily Starter',
    description: 'Complete your first daily problem.',
    rarity: 'common',
    category: 'practice',
    metric: 'dailyProblemsCompleted',
    threshold: 1,
    points: 25,
    sortOrder: 60,
  },
  {
    code: 'daily-streak-7',
    name: 'Week Warrior',
    description: 'Reach a seven-day daily problem streak.',
    rarity: 'rare',
    category: 'practice',
    metric: 'dailyStreakLongest',
    threshold: 7,
    points: 100,
    sortOrder: 61,
  },
  {
    code: 'daily-streak-14',
    name: 'Two-Week Grinder',
    description: 'Reach a fourteen-day daily problem streak.',
    rarity: 'rare',
    category: 'practice',
    metric: 'dailyStreakLongest',
    threshold: 14,
    points: 175,
    sortOrder: 62,
  },
  {
    code: 'daily-streak-30',
    name: 'Monthly Machine',
    description: 'Reach a thirty-day daily problem streak.',
    rarity: 'epic',
    category: 'practice',
    metric: 'dailyStreakLongest',
    threshold: 30,
    points: 300,
    sortOrder: 63,
  },
  {
    code: 'daily-streak-100',
    name: 'Century Streak',
    description: 'Reach a hundred-day daily problem streak.',
    rarity: 'legendary',
    category: 'practice',
    metric: 'dailyStreakLongest',
    threshold: 100,
    points: 750,
    sortOrder: 64,
  },
  {
    code: 'daily-completed-25',
    name: 'Daily Devotee',
    description: 'Complete twenty-five daily problems.',
    rarity: 'rare',
    category: 'practice',
    metric: 'dailyProblemsCompleted',
    threshold: 25,
    points: 150,
    sortOrder: 65,
  },
  {
    code: 'daily-completed-100',
    name: 'Daily Champion',
    description: 'Complete one hundred daily problems.',
    rarity: 'legendary',
    category: 'practice',
    metric: 'dailyProblemsCompleted',
    threshold: 100,
    points: 500,
    sortOrder: 66,
  },

  // ── Competitions ────────────────────────────────────────────────────────────
  {
    code: 'contest-debut',
    name: 'Contest Debut',
    description: 'Participate in your first contest.',
    rarity: 'common',
    category: 'competitions',
    metric: 'contestParticipations',
    threshold: 1,
    points: 50,
    sortOrder: 70,
  },
  {
    code: 'contest-triple',
    name: 'Contest Triple',
    description: 'Participate in three contests.',
    rarity: 'common',
    category: 'competitions',
    metric: 'contestParticipations',
    threshold: 3,
    points: 75,
    sortOrder: 71,
  },
  {
    code: 'contest-regular',
    name: 'Contest Regular',
    description: 'Participate in five contests.',
    rarity: 'rare',
    category: 'competitions',
    metric: 'contestParticipations',
    threshold: 5,
    points: 125,
    sortOrder: 72,
  },
  {
    code: 'arena-veteran',
    name: 'Arena Veteran',
    description: 'Participate in fifteen contests.',
    rarity: 'epic',
    category: 'competitions',
    metric: 'contestParticipations',
    threshold: 15,
    points: 275,
    sortOrder: 73,
  },
  {
    code: 'contest-marathon',
    name: 'Contest Marathon',
    description: 'Participate in thirty contests.',
    rarity: 'legendary',
    category: 'competitions',
    metric: 'contestParticipations',
    threshold: 30,
    points: 450,
    sortOrder: 74,
  },
  {
    code: 'contest-planner',
    name: 'Contest Planner',
    description: 'Bookmark five upcoming contests.',
    rarity: 'common',
    category: 'competitions',
    metric: 'contestBookmarks',
    threshold: 5,
    points: 40,
    sortOrder: 75,
  },
  {
    code: 'contest-tracker',
    name: 'Contest Tracker',
    description: 'Bookmark fifteen upcoming contests.',
    rarity: 'rare',
    category: 'competitions',
    metric: 'contestBookmarks',
    threshold: 15,
    points: 90,
    sortOrder: 76,
  },

  // ── Meta ────────────────────────────────────────────────────────────────────
  {
    code: 'badge-collector',
    name: 'Badge Collector',
    description: 'Earn five different badges.',
    rarity: 'epic',
    category: 'meta',
    metric: 'earnedBadges',
    threshold: 5,
    points: 150,
    sortOrder: 80,
  },
  {
    code: 'achievement-hunter',
    name: 'Achievement Hunter',
    description: 'Earn ten different badges.',
    rarity: 'rare',
    category: 'meta',
    metric: 'earnedBadges',
    threshold: 10,
    points: 200,
    sortOrder: 81,
  },
  {
    code: 'trophy-cabinet',
    name: 'Trophy Cabinet',
    description: 'Earn fifteen different badges.',
    rarity: 'epic',
    category: 'meta',
    metric: 'earnedBadges',
    threshold: 15,
    points: 300,
    sortOrder: 82,
  },
  {
    code: 'completionist',
    name: 'Completionist',
    description: 'Earn twenty different badges.',
    rarity: 'legendary',
    category: 'meta',
    metric: 'earnedBadges',
    threshold: 20,
    points: 500,
    sortOrder: 83,
  },
  {
    code: 'badge-maven',
    name: 'Badge Maven',
    description: 'Earn twenty-five different badges.',
    rarity: 'legendary',
    category: 'meta',
    metric: 'earnedBadges',
    threshold: 25,
    points: 600,
    sortOrder: 84,
  },
  {
    code: 'badge-legend',
    name: 'Badge Legend',
    description: 'Earn thirty-five different badges.',
    rarity: 'legendary',
    category: 'meta',
    metric: 'earnedBadges',
    threshold: 35,
    points: 800,
    sortOrder: 85,
  },
];

export const BADGE_CATALOG: BadgeSeed[] = assembleBadgeCatalog(
  LEGACY_BADGES,
  200,
);

const BOOLEAN_METRICS = new Set<BadgeMetric>([
  'githubLinked',
  'githubAppInstalled',
]);

export const BADGE_BY_CODE = new Map(BADGE_CATALOG.map((b) => [b.code, b]));

/** Prisma row fields only (BadgeSeed.metric is runtime-only). */
export function badgeSeedToDefinition(badge: BadgeSeed) {
  return {
    code: badge.code,
    name: badge.name,
    description: badge.description,
    rarity: badge.rarity,
    category: badge.category,
    threshold: badge.threshold,
    points: badge.points,
    sortOrder: badge.sortOrder,
  };
}

export function progressForMetric(
  metric: BadgeMetric,
  metrics: UserMetrics,
): number {
  const value = metrics[metric];
  if (BOOLEAN_METRICS.has(metric)) return value ? 1 : 0;
  return typeof value === 'number' ? value : 0;
}

export type UserMetrics = Record<BadgeMetric, number | boolean>;

export const LEVEL_THRESHOLDS = REPUTATION_LEVEL_THRESHOLDS;
export const LEVEL_NAMES = REPUTATION_LEVEL_NAMES;
export const computeLevel = computeReputationLevel;
export const getLevelName = getReputationLevelName;
export const getLevelProgress = getReputationLevelProgress;
