export const GAMIFICATION_POINTS_ENGINE = 'GAMIFICATION_POINTS_ENGINE';
export const GAMIFICATION_REPUTATION_SERVICE =
  'GAMIFICATION_REPUTATION_SERVICE';
export const GAMIFICATION_BADGE_EVALUATION = 'GAMIFICATION_BADGE_EVALUATION';
export const GAMIFICATION_LEADERBOARD = 'GAMIFICATION_LEADERBOARD';
export const ACTIVITY_EVENT_SERVICE = 'ACTIVITY_EVENT_SERVICE';
