export type Nibras75Entry = {
  rank: number;
  slug: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  description: string;
  tags: string[];
  askedByCount: number;
};

/** Curated interview list aligned with the Taro 75 / FAANG DSA set. */
export const NIBRAS_75_CURRICULUM: Nibras75Entry[] = [
  {
    rank: 1,
    slug: 'two-sum',
    title: 'Two Sum',
    difficulty: 'Easy',
    description:
      'Find two numbers that add up to a target and return their indices.',
    tags: ['array', 'hash-table'],
    askedByCount: 51,
  },
  {
    rank: 2,
    slug: 'lru-cache',
    title: 'LRU Cache',
    difficulty: 'Medium',
    description: 'Design a least-recently-used cache with get and put in O(1).',
    tags: ['linked-list', 'design', 'hash-table'],
    askedByCount: 64,
  },
  {
    rank: 3,
    slug: 'merge-intervals',
    title: 'Merge Intervals',
    difficulty: 'Medium',
    description: 'Merge all overlapping intervals in a collection.',
    tags: ['array', 'sorting'],
    askedByCount: 55,
  },
  {
    rank: 4,
    slug: 'best-time-to-buy-and-sell-stock',
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    description: 'Maximize profit with one buy and one sell.',
    tags: ['array', 'dynamic-programming'],
    askedByCount: 47,
  },
  {
    rank: 5,
    slug: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    description: 'Longest contiguous substring with all unique characters.',
    tags: ['string', 'sliding-window', 'hash-table'],
    askedByCount: 48,
  },
  {
    rank: 6,
    slug: 'valid-parentheses',
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    description: 'Check if brackets are opened and closed in valid order.',
    tags: ['string', 'stack'],
    askedByCount: 45,
  },
  {
    rank: 7,
    slug: 'number-of-islands',
    title: 'Number of Islands',
    difficulty: 'Medium',
    description: 'Count connected land regions in a grid.',
    tags: ['array', 'depth-first-search', 'breadth-first-search'],
    askedByCount: 58,
  },
  {
    rank: 8,
    slug: 'group-anagrams',
    title: 'Group Anagrams',
    difficulty: 'Medium',
    description: 'Group words that are anagrams of each other.',
    tags: ['array', 'string', 'hash-table'],
    askedByCount: 47,
  },
  {
    rank: 9,
    slug: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    description: 'Compute how much water can be trapped after rain.',
    tags: ['array', 'two-pointers', 'stack'],
    askedByCount: 38,
  },
  {
    rank: 10,
    slug: 'longest-palindromic-substring',
    title: 'Longest Palindromic Substring',
    difficulty: 'Medium',
    description: 'Find the longest palindromic substring.',
    tags: ['string', 'dynamic-programming'],
    askedByCount: 36,
  },
  {
    rank: 11,
    slug: 'top-k-frequent-elements',
    title: 'Top K Frequent Elements',
    difficulty: 'Medium',
    description: 'Return the k most frequent elements.',
    tags: ['array', 'hash-table', 'heap'],
    askedByCount: 35,
  },
  {
    rank: 12,
    slug: 'median-of-two-sorted-arrays',
    title: 'Median of Two Sorted Arrays',
    difficulty: 'Hard',
    description: 'Find the median of two sorted arrays.',
    tags: ['array', 'binary-search'],
    askedByCount: 27,
  },
  {
    rank: 13,
    slug: '3sum',
    title: '3Sum',
    difficulty: 'Medium',
    description: 'Find unique triplets that sum to zero.',
    tags: ['array', 'two-pointers', 'sorting'],
    askedByCount: 29,
  },
  {
    rank: 14,
    slug: 'subarray-sum-equals-k',
    title: 'Subarray Sum Equals K',
    difficulty: 'Medium',
    description: 'Count subarrays with sum equal to k.',
    tags: ['array', 'hash-table', 'prefix-sum'],
    askedByCount: 28,
  },
  {
    rank: 15,
    slug: 'merge-k-sorted-lists',
    title: 'Merge k Sorted Lists',
    difficulty: 'Hard',
    description: 'Merge k sorted linked lists into one sorted list.',
    tags: ['linked-list', 'heap'],
    askedByCount: 33,
  },
  {
    rank: 16,
    slug: 'longest-common-prefix',
    title: 'Longest Common Prefix',
    difficulty: 'Easy',
    description: 'Longest prefix shared by all strings.',
    tags: ['string', 'trie'],
    askedByCount: 26,
  },
  {
    rank: 17,
    slug: 'search-in-rotated-sorted-array',
    title: 'Search in Rotated Sorted Array',
    difficulty: 'Medium',
    description: 'Search a target in a rotated sorted array.',
    tags: ['array', 'binary-search'],
    askedByCount: 30,
  },
  {
    rank: 18,
    slug: 'maximum-subarray',
    title: 'Maximum Subarray',
    difficulty: 'Medium',
    description: 'Find the contiguous subarray with largest sum.',
    tags: ['array', 'dynamic-programming'],
    askedByCount: 34,
  },
  {
    rank: 19,
    slug: 'rotate-image',
    title: 'Rotate Image',
    difficulty: 'Medium',
    description: 'Rotate an n×n matrix 90 degrees clockwise in place.',
    tags: ['array', 'math'],
    askedByCount: 24,
  },
  {
    rank: 20,
    slug: 'spiral-matrix',
    title: 'Spiral Matrix',
    difficulty: 'Medium',
    description: 'Return matrix elements in spiral order.',
    tags: ['array', 'matrix'],
    askedByCount: 27,
  },
  {
    rank: 21,
    slug: 'add-two-numbers',
    title: 'Add Two Numbers',
    difficulty: 'Medium',
    description: 'Add two numbers represented as linked lists.',
    tags: ['linked-list', 'math'],
    askedByCount: 16,
  },
  {
    rank: 22,
    slug: 'kth-largest-element-in-an-array',
    title: 'Kth Largest Element in an Array',
    difficulty: 'Medium',
    description: 'Find the kth largest element in an unsorted array.',
    tags: ['array', 'heap', 'quickselect'],
    askedByCount: 25,
  },
  {
    rank: 23,
    slug: 'generate-parentheses',
    title: 'Generate Parentheses',
    difficulty: 'Medium',
    description: 'Generate all combinations of n pairs of valid parentheses.',
    tags: ['string', 'backtracking'],
    askedByCount: 22,
  },
  {
    rank: 24,
    slug: 'rotting-oranges',
    title: 'Rotting Oranges',
    difficulty: 'Medium',
    description: 'Minimum time until all oranges rot in a grid.',
    tags: ['array', 'breadth-first-search'],
    askedByCount: 25,
  },
  {
    rank: 25,
    slug: 'find-first-and-last-position-of-element-in-sorted-array',
    title: 'Find First and Last Position of Element in Sorted Array',
    difficulty: 'Medium',
    description: 'Find start and end indices of target in sorted array.',
    tags: ['array', 'binary-search'],
    askedByCount: 18,
  },
  {
    rank: 26,
    slug: 'merge-sorted-array',
    title: 'Merge Sorted Array',
    difficulty: 'Easy',
    description: 'Merge nums2 into nums1 in sorted order in-place.',
    tags: ['array', 'two-pointers'],
    askedByCount: 22,
  },
  {
    rank: 27,
    slug: 'roman-to-integer',
    title: 'Roman to Integer',
    difficulty: 'Easy',
    description: 'Convert a Roman numeral string to an integer.',
    tags: ['string', 'math'],
    askedByCount: 19,
  },
  {
    rank: 28,
    slug: 'house-robber',
    title: 'House Robber',
    difficulty: 'Medium',
    description: 'Maximize robbery loot without adjacent houses.',
    tags: ['array', 'dynamic-programming'],
    askedByCount: 28,
  },
  {
    rank: 29,
    slug: 'palindrome-number',
    title: 'Palindrome Number',
    difficulty: 'Easy',
    description: 'Determine if an integer is a palindrome.',
    tags: ['math'],
    askedByCount: 13,
  },
  {
    rank: 30,
    slug: 'move-zeroes',
    title: 'Move Zeroes',
    difficulty: 'Easy',
    description: 'Move all zeros to the end while preserving order.',
    tags: ['array', 'two-pointers'],
    askedByCount: 22,
  },
  {
    rank: 31,
    slug: 'container-with-most-water',
    title: 'Container With Most Water',
    difficulty: 'Medium',
    description: 'Maximize water held between vertical lines.',
    tags: ['array', 'two-pointers'],
    askedByCount: 26,
  },
  {
    rank: 32,
    slug: 'meeting-rooms-ii',
    title: 'Meeting Rooms II',
    difficulty: 'Medium',
    description: 'Minimum conference rooms for overlapping meetings.',
    tags: ['array', 'heap', 'sorting'],
    askedByCount: 31,
  },
  {
    rank: 33,
    slug: 'coin-change',
    title: 'Coin Change',
    difficulty: 'Medium',
    description: 'Minimum coins needed to make an amount.',
    tags: ['dynamic-programming', 'breadth-first-search'],
    askedByCount: 23,
  },
  {
    rank: 34,
    slug: 'valid-anagram',
    title: 'Valid Anagram',
    difficulty: 'Easy',
    description: 'Check if two strings are anagrams.',
    tags: ['string', 'hash-table'],
    askedByCount: 20,
  },
  {
    rank: 35,
    slug: 'product-of-array-except-self',
    title: 'Product of Array Except Self',
    difficulty: 'Medium',
    description: 'Product of all elements except self without division.',
    tags: ['array', 'prefix-sum'],
    askedByCount: 26,
  },
  {
    rank: 36,
    slug: 'longest-consecutive-sequence',
    title: 'Longest Consecutive Sequence',
    difficulty: 'Medium',
    description: 'Length of longest consecutive elements sequence.',
    tags: ['array', 'hash-table'],
    askedByCount: 24,
  },
  {
    rank: 37,
    slug: 'koko-eating-bananas',
    title: 'Koko Eating Bananas',
    difficulty: 'Medium',
    description: 'Minimum eating speed to finish piles in h hours.',
    tags: ['array', 'binary-search'],
    askedByCount: 23,
  },
  {
    rank: 38,
    slug: 'jump-game',
    title: 'Jump Game',
    difficulty: 'Medium',
    description: 'Can you reach the last index from the first?',
    tags: ['array', 'greedy'],
    askedByCount: 19,
  },
  {
    rank: 39,
    slug: 'integer-to-roman',
    title: 'Integer to Roman',
    difficulty: 'Medium',
    description: 'Convert an integer to a Roman numeral.',
    tags: ['string', 'math'],
    askedByCount: 22,
  },
  {
    rank: 40,
    slug: 'course-schedule',
    title: 'Course Schedule',
    difficulty: 'Medium',
    description: 'Can you finish all courses given prerequisites?',
    tags: ['depth-first-search', 'breadth-first-search', 'graph'],
    askedByCount: 27,
  },
  {
    rank: 41,
    slug: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    difficulty: 'Hard',
    description: 'Smallest substring of s containing all characters of t.',
    tags: ['string', 'sliding-window', 'hash-table'],
    askedByCount: 19,
  },
  {
    rank: 42,
    slug: 'reverse-linked-list',
    title: 'Reverse Linked List',
    difficulty: 'Easy',
    description: 'Reverse a singly linked list.',
    tags: ['linked-list', 'recursion'],
    askedByCount: 19,
  },
  {
    rank: 43,
    slug: 'next-permutation',
    title: 'Next Permutation',
    difficulty: 'Medium',
    description:
      'Rearrange nums into the next lexicographically greater permutation.',
    tags: ['array', 'two-pointers'],
    askedByCount: 15,
  },
  {
    rank: 44,
    slug: 'sliding-window-maximum',
    title: 'Sliding Window Maximum',
    difficulty: 'Hard',
    description: 'Max in each sliding window of size k.',
    tags: ['array', 'sliding-window', 'heap'],
    askedByCount: 24,
  },
  {
    rank: 45,
    slug: 'course-schedule-ii',
    title: 'Course Schedule II',
    difficulty: 'Medium',
    description: 'Return a valid order to take all courses.',
    tags: ['depth-first-search', 'breadth-first-search', 'graph'],
    askedByCount: 28,
  },
  {
    rank: 46,
    slug: 'merge-two-sorted-lists',
    title: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    description: 'Merge two sorted linked lists.',
    tags: ['linked-list', 'recursion'],
    askedByCount: 23,
  },
  {
    rank: 47,
    slug: 'valid-palindrome',
    title: 'Valid Palindrome',
    difficulty: 'Easy',
    description: 'Is string a palindrome after ignoring non-alphanumeric?',
    tags: ['two-pointers', 'string'],
    askedByCount: 17,
  },
  {
    rank: 48,
    slug: 'remove-duplicates-from-sorted-array',
    title: 'Remove Duplicates from Sorted Array',
    difficulty: 'Easy',
    description: 'Remove duplicates in-place from sorted array.',
    tags: ['array', 'two-pointers'],
    askedByCount: 12,
  },
  {
    rank: 49,
    slug: 'find-peak-element',
    title: 'Find Peak Element',
    difficulty: 'Medium',
    description: 'Find any peak element index.',
    tags: ['array', 'binary-search'],
    askedByCount: 17,
  },
  {
    rank: 50,
    slug: 'word-ladder',
    title: 'Word Ladder',
    difficulty: 'Hard',
    description: 'Shortest transformation sequence from beginWord to endWord.',
    tags: ['breadth-first-search', 'hash-table', 'string'],
    askedByCount: 21,
  },
  {
    rank: 51,
    slug: 'best-time-to-buy-and-sell-stock-ii',
    title: 'Best Time to Buy and Sell Stock II',
    difficulty: 'Medium',
    description: 'Maximize profit with unlimited transactions.',
    tags: ['array', 'greedy', 'dynamic-programming'],
    askedByCount: 17,
  },
  {
    rank: 52,
    slug: 'subsets',
    title: 'Subsets',
    difficulty: 'Medium',
    description: 'Return all possible subsets (power set).',
    tags: ['array', 'backtracking', 'bit-manipulation'],
    askedByCount: 14,
  },
  {
    rank: 53,
    slug: 'rotate-array',
    title: 'Rotate Array',
    difficulty: 'Medium',
    description: 'Rotate array to the right by k steps.',
    tags: ['array', 'math'],
    askedByCount: 21,
  },
  {
    rank: 54,
    slug: 'min-stack',
    title: 'Min Stack',
    difficulty: 'Medium',
    description: 'Stack supporting push, pop, top, and getMin in O(1).',
    tags: ['stack', 'design'],
    askedByCount: 17,
  },
  {
    rank: 55,
    slug: 'word-break',
    title: 'Word Break',
    difficulty: 'Medium',
    description: 'Can string be segmented into dictionary words?',
    tags: ['array', 'dynamic-programming', 'string'],
    askedByCount: 21,
  },
  {
    rank: 56,
    slug: 'word-search',
    title: 'Word Search',
    difficulty: 'Medium',
    description: 'Find if word exists in a 2D board.',
    tags: ['array', 'backtracking', 'matrix'],
    askedByCount: 22,
  },
  {
    rank: 57,
    slug: 'contains-duplicate',
    title: 'Contains Duplicate',
    difficulty: 'Easy',
    description: 'Return true if any value appears at least twice.',
    tags: ['array', 'hash-table'],
    askedByCount: 15,
  },
  {
    rank: 58,
    slug: 'longest-increasing-subsequence',
    title: 'Longest Increasing Subsequence',
    difficulty: 'Medium',
    description: 'Length of longest strictly increasing subsequence.',
    tags: ['array', 'binary-search', 'dynamic-programming'],
    askedByCount: 21,
  },
  {
    rank: 59,
    slug: 'reorganize-string',
    title: 'Reorganize String',
    difficulty: 'Medium',
    description: 'Rearrange so no two adjacent chars are equal.',
    tags: ['string', 'greedy', 'heap'],
    askedByCount: 18,
  },
  {
    rank: 60,
    slug: 'climbing-stairs',
    title: 'Climbing Stairs',
    difficulty: 'Easy',
    description: 'Ways to climb n stairs taking 1 or 2 steps.',
    tags: ['dynamic-programming', 'math'],
    askedByCount: 17,
  },
  {
    rank: 61,
    slug: 'string-compression',
    title: 'String Compression',
    difficulty: 'Medium',
    description: 'Compress string with run-length encoding in-place.',
    tags: ['array', 'two-pointers', 'string'],
    askedByCount: 24,
  },
  {
    rank: 62,
    slug: 'sort-colors',
    title: 'Sort Colors',
    difficulty: 'Medium',
    description: 'Sort array of 0s, 1s, and 2s in-place.',
    tags: ['array', 'two-pointers', 'sorting'],
    askedByCount: 21,
  },
  {
    rank: 63,
    slug: 'jump-game-ii',
    title: 'Jump Game II',
    difficulty: 'Medium',
    description: 'Minimum jumps to reach the last index.',
    tags: ['array', 'greedy'],
    askedByCount: 18,
  },
  {
    rank: 64,
    slug: 'decode-string',
    title: 'Decode String',
    difficulty: 'Medium',
    description: 'Decode k[encoded_string] patterns.',
    tags: ['string', 'stack'],
    askedByCount: 21,
  },
  {
    rank: 65,
    slug: 'binary-tree-maximum-path-sum',
    title: 'Binary Tree Maximum Path Sum',
    difficulty: 'Hard',
    description: 'Max path sum in a binary tree (any nodes).',
    tags: ['tree', 'depth-first-search', 'dynamic-programming'],
    askedByCount: 20,
  },
  {
    rank: 66,
    slug: 'copy-list-with-random-pointer',
    title: 'Copy List with Random Pointer',
    difficulty: 'Medium',
    description: 'Deep copy a linked list with random pointers.',
    tags: ['linked-list', 'hash-table'],
    askedByCount: 16,
  },
  {
    rank: 67,
    slug: 'valid-sudoku',
    title: 'Valid Sudoku',
    difficulty: 'Medium',
    description: 'Validate a partially filled Sudoku board.',
    tags: ['array', 'hash-table', 'matrix'],
    askedByCount: 20,
  },
  {
    rank: 68,
    slug: 'letter-combinations-of-a-phone-number',
    title: 'Letter Combinations of a Phone Number',
    difficulty: 'Medium',
    description: 'All letter combinations from phone digits.',
    tags: ['string', 'backtracking'],
    askedByCount: 23,
  },
  {
    rank: 69,
    slug: 'daily-temperatures',
    title: 'Daily Temperatures',
    difficulty: 'Medium',
    description: 'Days until a warmer temperature for each day.',
    tags: ['array', 'stack', 'monotonic-stack'],
    askedByCount: 22,
  },
  {
    rank: 70,
    slug: 'candy',
    title: 'Candy',
    difficulty: 'Hard',
    description: 'Minimum candies so higher-rated neighbors get more.',
    tags: ['array', 'greedy'],
    askedByCount: 13,
  },
  {
    rank: 71,
    slug: 'powx-n',
    title: 'Pow(x, n)',
    difficulty: 'Medium',
    description: 'Compute x raised to the power n.',
    tags: ['math', 'recursion'],
    askedByCount: 13,
  },
  {
    rank: 72,
    slug: 'lfu-cache',
    title: 'LFU Cache',
    difficulty: 'Hard',
    description: 'Design a least-frequently-used cache.',
    tags: ['design', 'hash-table', 'linked-list'],
    askedByCount: 16,
  },
  {
    rank: 73,
    slug: 'simplify-path',
    title: 'Simplify Path',
    difficulty: 'Medium',
    description: 'Simplify a Unix-style absolute path.',
    tags: ['string', 'stack'],
    askedByCount: 14,
  },
  {
    rank: 74,
    slug: 'basic-calculator',
    title: 'Basic Calculator',
    difficulty: 'Hard',
    description: 'Evaluate expression with +, -, and parentheses.',
    tags: ['string', 'stack'],
    askedByCount: 18,
  },
  {
    rank: 75,
    slug: 'majority-element',
    title: 'Majority Element',
    difficulty: 'Easy',
    description: 'Find element appearing more than n/2 times.',
    tags: ['array', 'hash-table'],
    askedByCount: 13,
  },
];

export const NIBRAS_75_TOTAL = NIBRAS_75_CURRICULUM.length;
